import { Product } from "./types";

export const products: Product[] = [
    {
      id: 1,
      name: "Rice",
      quantity: 10,
      price: 10.99,
      total: 109.90,
    },
    {
      id: 2,
      name: "Wheat Flour",
      quantity: 5,
      price: 5.99,
      total: 29.95,
    },
    {
      id: 3,
      name: "Sugar",
      quantity: 20,
      price: 2.99,
      total: 59.80,
    },
    {
      id: 4,
      name: "Salt",
      quantity: 15,
      price: 1.99,
      total: 29.85,
    },
    {
      id: 5,
      name: "Tomatoes",
      quantity: 12,
      price: 3.99,
      total: 47.88,
    },
    {
      id: 6,
      name: "Onions",
      quantity: 18,
      price: 2.49,
      total: 44.82,
    },
    {
      id: 7,
      name: "Potatoes",
      quantity: 25,
      price: 1.99,
      total: 49.75,
    },
    {
      id: 8,
      name: "Carrots",
      quantity: 15,
      price: 1.99,
      total: 29.85,
    },
    {
      id: 9,
      name: "Apples",
      quantity: 20,
      price: 2.99,
      total: 59.80,
    },
    {
      id: 10,
      name: "Bananas",
      quantity: 30,
      price: 1.49,
      total: 44.70,
    },
    {
      id: 11,
      name: "Milk",
      quantity: 10,
      price: 3.99,
      total: 39.90,
    },
    {
      id: 12,
      name: "Eggs",
      quantity: 12,
      price: 2.99,
      total: 35.88,
    },
    {
      id: 13,
      name: "Chicken Breast",
      quantity: 5,
      price: 9.99,
      total: 49.95,
    },
    {
      id: 14,
      name: "Ground Beef",
      quantity: 10,
      price: 7.99,
      total: 79.90,
    },
    {
      id: 15,
      name: "Pasta",
      quantity: 20,
      price: 2.99,
      total: 59.80,
    },
    {
      id: 16,
      name: "Bread",
      quantity: 15,
      price: 1.99,
      total: 29.85,
    },
    {
      id: 17,
      name: "Butter",
      quantity: 10,
      price: 3.99,
      total: 39.90,
    },
    {
      id: 18,
      name: "Cheese",
      quantity: 5,
      price: 5.99,
      total: 29.95,
    },
    {
      id: 19,
      name: "Yogurt",
      quantity: 12,
      price: 2.99,
      total: 35.88,
    },
    {
      id: 20,
      name: "Coffee",
      quantity: 20,
      price: 2.99,
      total: 59.80,
    },
  ];
  